### ISSUE TITLE
Pre-trained Model and Code for Audio-Visual Wake Work Spotting

### ISSUE THREAD

**Issue by saurabh-shandilya** [LianjiaTech/athena#1]
Hi, 

Thanks for sharing your paper and code. The results in the paper look impressive. If I want to reproduce these results - is there a pre-trained model (tf or tflite) available? Some steps are mentioned in https://github.com/LianjiaTech/athena/tree/main/examples/kws but not sure where I can find the folder athena_wakeup and files athena_wakeup/main.py, athena_wakeup/test_main.py, athena_wakeup/test_main_av.py?

**Comment by JianweiSun007** [comment]
Hi, thanks for your care, the [examples/kws](https://github.com/LianjiaTech/athena/tree/main/examples/kws) is updated, and the pre-trained models of KWS are not released at this time.

**Comment by saurabh-shandilya** [comment]
@JianweiSun007 Thanks a lot for a quick response. Really appreciate it!

**Comment by saurabh-shandilya** [comment]
@JianweiSun007 Just one more clarification. Is the main.py script mentioned for training same as that in https://github.com/LianjiaTech/athena/blob/main/athena/main.py? Since the model is not released, I would like to try the training steps mentioned in the updated README. Thanks once again.

**Comment by JianweiSun007** [comment]
Yes, you can use this https://github.com/LianjiaTech/athena/blob/main/athena/main.py script.
